package com.eloueduniv.monsit.domain.usecase

import android.os.Environment
import com.eloueduniv.monsit.data.local.AudioFileDataSource
import com.eloueduniv.monsit.data.local.CallLogDataSource
import com.eloueduniv.monsit.data.model.Call
import com.eloueduniv.monsit.data.repository.CallRepository
import kotlinx.coroutines.flow.first
import javax.inject.Inject
import kotlin.math.abs
import java.io.File

class SyncCallsUseCase @Inject constructor(
    private val callRepository: CallRepository,
    private val callLogDataSource: CallLogDataSource,
    private val audioFileDataSource: AudioFileDataSource,
    private val processCallUseCase: ProcessCallUseCase
) {
    suspend operator fun invoke() {
        // 1. Fetch recent call logs from system
        val recentLogs = callLogDataSource.getRecentCallLogs(5)
        
        // 2. Fetch existing calls from our database
        var currentCallsInDb = callRepository.getCalls().first()

        for (log in recentLogs) {
            // 3. Check if this call is already processed (within a 5s window for better precision)
            val alreadyProcessed = currentCallsInDb.any { abs(it.startTime - log.date) < 5000 }
            if (alreadyProcessed) continue

            // 4. Try to find a matching audio file in MediaStore
            val audioPath = audioFileDataSource.findMatchingAudio(log.number, log.date)

            //audioPath = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "egypt_call.wav").absolutePath

            // 5. Create and save the new call entity (even if audioPath is null)
            val newCall = Call(
                id = 0, // Auto-generated by Room
                contactName = log.name ?: log.number,
                startTime = log.date,
                duration = log.duration,
                audioUrl = audioPath ?: "", // Use empty string if no audio found
                transcript = "", // Initially empty
                summary = "",    // Initially empty
                contactId = 0,   // Placeholder
                note = null
            )

            val generatedId = callRepository.addCall(newCall)
            val callToProcess = newCall.copy(id = generatedId)

            // Update local cache to prevent duplicates in the same loop
            currentCallsInDb = currentCallsInDb + callToProcess

            // 6. Trigger AI processing only if we have an audio file
            if (audioPath != null) {
                processCallUseCase(audioPath).collect { state ->
                    when (state) {
                        is ProcessState.Success -> {
                            val finalCall = callToProcess.copy(
                                transcript = state.result.transcript,
                                summary = state.result.summary
                            )
                            callRepository.updateCall(finalCall)
                        }
                        is ProcessState.Error -> {
                            // Log error
                        }
                        else -> { /* In progress states */ }
                    }
                }
            }
        }
    }
}
